---
title: "Gapminder analysis"
author: "Andy Teucher"
date: "22/04/2020"
output: html_document
---

```{r load}
library(readr)
library(dplyr)
library(ggplot2)
gapminder <- read_csv("data/gapminder_data.csv")
```

```{r filter-can}
canada <- filter(gapminder, country == "Canada")
```

```{r plot-1}
ggplot(canada, aes(x = lifeExp, y = gdpPercap)) + 
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r model}
canada_lm <- lm(gdpPercap ~ lifeExp, data = canada)
summary(canada_lm)
```

```{r diagnostics}
plot(canada_lm)
```

```{r broom}
library(broom)
model_summary <- glance(canada_lm)
model_summary
model_terms <- tidy(canada_lm)
model_terms
model_predict <- augment(canada_lm)
model_predict
```

```{r plot-lm}
ggplot() + 
  geom_point(data = canada, aes(x = lifeExp, y = gdpPercap)) + 
  geom_line(data = model_predict, aes(x = lifeExp, y = .fitted))
```

```{r plot-ci, echo=FALSE}
model_predict <- model_predict %>% 
  mutate(lower_ci = .fitted - 1.96 * .se.fit, 
         upper_ci = .fitted + 1.96 * .se.fit)

ggplot() + 
  geom_ribbon(data = model_predict, aes(x = lifeExp, ymin = lower_ci, ymax = upper_ci), alpha = 0.2) + 
  geom_point(data = canada, aes(x = lifeExp, y = gdpPercap)) + 
  geom_line(data = model_predict, aes(x = lifeExp, y = .fitted))
```


```{r model-stats, echo=FALSE}
r2 <- round(model_summary$adj.r.squared, 2)
sig_0.05 <- ifelse(model_summary$p.value < 0.05, "p < 0.05", "p > 0.05")

ggplot() + 
  geom_ribbon(data = model_predict, aes(x = lifeExp, ymin = lower_ci, ymax = upper_ci), alpha = 0.2) + 
  geom_point(data = canada, aes(x = lifeExp, y = gdpPercap)) + 
  geom_line(data = model_predict, aes(x = lifeExp, y = .fitted)) + 
  geom_text(aes(x = 72, y = 30000), label = paste0("R^2 = ", r2, "; ", sig_0.05))
```

```{r lifeExp-stats, echo=FALSE}
life_exp <- filter(model_terms, term == "lifeExp")
life_exp_estimate <- round(life_exp$estimate, 1)
life_exp_se <- round(life_exp$std.error, 1)
```

The predicted effect of life expectancy on per-capita GDP is `r life_exp_estimate` 
(SE: `r life_exp_se`), meaning that for every year we live longer, our per-capita 
GDP increases by approximately `r life_exp_esimate`.
