on: [push, pull_request]

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Make Rprofile
        run: |
          cat <<EOT >> .Rprofile
          options(crayon.enabled = FALSE)
          ## Choose cran mirror
          local({
          	r = getOption("repos")
          	r["CRAN"] = "https://cran.rstudio.com/"
          	options(repos = r)
          })
          EOT

      - name: Install packages
        run: |
          R -e 'install.packages("sf", type = "binary")'
          R -e 'install.packages(c("tidyverse", "reprex", "bookdown", "bcdata", "mapview", "bslib", "downlit", "nycflights13"))'

      - name: Build site
        run: R -e 'bookdown::render_book("index.Rmd")'

      - name: Commit bookdown
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add docs
            git commit -m 'build gitbook'
            git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
          fi

      - name: Update notes
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: bash bin/skeleton.sh
        shell: bash

      - name: Make course zip
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: Rscript make_course_zip.R

      - name: Commit course zip
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add intro-to-r-course-notes/. intro-to-r-course-notes.zip
            git commit -m 'make course zipfile'
            git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
          fi
