on: [push]

name: skeleton-notes

jobs:
  job1:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test step
        if: github.ref == 'refs/heads/workflow-run' && github.event_name == 'push'
        run: bash bin/helloworld.sh
        shell: bash

      - name: Commit test
        if: github.ref == 'refs/heads/workflow-run' && github.event_name == 'push'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add intro-to-r-course-notes/.
            git commit -m 'add test file'
            git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
          fi

