on: [push]
# this file requires the following work:
# move "Make course zip" into a shell script so to avoid
# installing R and packages onto runner.

name: skeleton-notes

jobs:
  make-skeleton-notes:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

#      - name: Update notes
#        run: bash bin/skeleton.sh
#        shell: bash

#      - name: Commit updated notes
#        run: |
#          if [[ -n "$(git status --porcelain)" ]]; then
#            git add .
#            git commit -m 'update skeleton notes'
#            git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
#          fi

#      - name: Make course zip
#        run: Rscript make_course_zip.R

#      - name: Commit course zip
#        run: |
#          if [[ -n "$(git status --porcelain)" ]]; then
#            git add intro-to-r-course-notes/. intro-to-r-course-notes.zip
#            git commit -m 'make course zipfile'
#            git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
#          fi
