on: [push]

name: skeleton-notes

jobs:
  job1:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: test step
        run: cp index.Rmd intro-to-r-course-notes/

